kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        "requestheader-username-headers": "X-Remote-User"
        "requestheader-group-headers": "X-Remote-Group"
        "requestheader-client-ca-file": "/etc/kubernetes/pki/front-proxy-ca.crt"
        "audit-policy-file": "/mount/audit-policy.yaml"
        "audit-log-path": "/mount/kube-apiserver-audit.log"
        "audit-log-maxsize": "50"
        "audit-log-maxbackup": "1"
        "v": "4"
      extraVolumes:
      - hostPath: /mount
        mountPath: /mount
        name: authenticating-proxy-files
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: "/Users/micahhausler/go/src/github.com/micahhausler/httpsig-scratch/mount"
        containerPath: "/mount"
